[project]
name = "custom-rasterizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
[build-system]
requires = [
    "setuptools",
    "wheel",
    "torch",          # Add torch explicitly
    "ninja",
    "numpy"
]